import AppBar from "@/components/AppBar";
import "./globals.css";
import Providers from "@/components/Providers";
import { Jost } from 'next/font/google'


export const metadata = {
  title: "Next-Auth Tutorial",
  description: "Generated by Sakura Dev",
};

const inter = Jost({ subsets: ['latin'] })

interface Props {
  children: React.ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Providers>
    <AppBar />
    {props.children}
    </Providers>
    </body>
    </html>
    );
  }
  